backend:
  name: github
  repo: "blindstone2026-commits/blind-stone-website"
  branch: "main"

# 🚀 圖片極速引擎 (Cloudinary)
media_library:
  name: cloudinary
  config:
    cloud_name: 'avwvv663'
    api_key: '554978162891374'
    multiple: true

publish_mode: simple
show_published_group: false

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: "articles"
    label: "文章"
    folder: "content/articles"
    create: true
    summary: "【{{main_category}}】 {{title}}"
    fields:
      - {label: "文章標題", name: "title", widget: "string"}
      - label: "發布日期"
        name: "date"
        widget: "datetime"
        date_format: "YYYY-MM-DD"
        time_format: false
        format: "YYYY-MM-DD"
      - {label: "封面大圖", name: "thumbnail", widget: "image"}
      - label: "大分類"
        name: "main_category"
        widget: "select"
        multiple: true
        options: ["What's On", "The Creatives", "Spaces", "The Guide"]
      - label: "小分類"
        name: "sub_category"
        widget: "select"
        multiple: true
        options: ["Event", "News", "Special", "Master", "New Stars", "Editor Special", "Gallery", "Art Cafe", "Art Special", "無"]
      - label: "文章內文"
        name: "body"
        widget: "markdown"
        minimal: false 
        buttons: ["bold", "italic", "code", "link", "heading-one", "heading-two", "heading-three", "quote", "bulleted-list", "numbered-list"]
        editor_components: ["image"]
        modes: ["rich_text"]
